baseURL = "https://VivianaCarcaiso.github.io/"
languageCode = "en-us"
title = "My Bark Website"
theme = "barks"

# Enable the CSS/JS pipeline from Hugo Extended
# (You MUST use the extended version)
[build]
  writeStats = true

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark.renderer]
    unsafe = true
