baseURL = "https://VivianaCarcaiso.github.io/"
languageCode = "en-us"
title = "Viviana Carcaiso"
theme = "barks"

# Enable the CSS/JS pipeline from Hugo Extended
# (You MUST use the extended version)
[build]
  writeStats = true

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark.renderer]
    unsafe = true

[params.typography]
    title_font = "Montserrat"
    body_font = "Kedebideri"

[params.colors]
    theme_color = "#333333"
    background_color = "#fcfbf9"
    text_color = "#333333"
    link_color = "#95a3ba"

[params.social]
    [params.social.linkedin]
        name = "LinkedIn"
        class = "fas fa-linkedin"
        url = "https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://fr.linkedin.com/in/viviana-carcaiso-77918a225&ved=2ahUKEwin_pS694yRAxV1TaQEHau1BjgQFnoECCMQAQ&usg=AOvVaw292-5v9552B7AuCARiL7jD"
        weight = 1
    [params.social.github]
        name = "GitHub"
        class = "fab fa-github"
        url = "https://github.com/VivianaCarcaiso"
        weight = 3
    [params.social.google_scholar]
        name = "Google Scholar"
        class = "ai ai-google-scholar-square"
        url = "https://scholar.google.com/citations?user=9QG1j3YAAAAJ&hl=it"
        weight = 2

[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 2

  [[menu.main]]
    name = "CV"
    url = "/cv.pdf"
    weight = 3

[params]
  description = "My personal website"
  author = "Viviana Carcaiso"
